name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Crystal
      uses: oprypin/install-crystal@v1
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Generate docs
      run: crystal doc
    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && runner.os == 'Linux'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        SINGLE_COMMIT: true
